const resources = {
    en: {
        translation: {
            lang : 'English',
            home: 'Home',
            exp: "Experiences",
comp: "Skills",
prjs: "Projects",
parc: "Career Path",
            pers: 'Personal',
            prof: 'Professional',
            contact: 'Contact',
            nom: "ILYAS MAKHLOUL ",
            CompTech : "Technical Skills",
            ExpProf : "Professional Experience", 
            statut: "Engineering student in Computer Engineering at the National School of Applied Sciences of Fes, and I am looking for a final-year internship (6 months starting from January 2025).",
            DownCV: "Download CV",
            DownST: "Internship Application",
            etud: 'Engineering student',
            tel: 'Telephone',
            email: 'Email',
            loc: 'Location',
            addr: 'Fes, Morocco',
            DownCVA: 'Download CV in English',
            prof : 'Profile',
            prof1: "I am a computer engineering student in the third year of the engineering cycle at the National School of Applied Sciences of Fès (Bac +5). I am a passionate programmer with proficiency in several programming languages.",
            prof2: "My particular interest lies in the development of web/Android applications and games, and everything related to AI - Machine learning - Deep Learning.",
            do: "What I do !!!",
            AI: "AI Machine Learning",
            AIdesc: "I am currently learning technologies related to AI, machine learning (regression/classification) in Python.",
            AppDev: "App Development",
            AppDevDesc: "I have developed several desktop and Android applications. You can see them in the projects section below.",
            API: 'API Development',
            APIdesc: "I have worked with hotel APIs during the development of EasyStay during my internship.",
            WebDev: "Web Development",
            WebDevDesc: "I have developed several web applications using various technologies such as ASP.NET Core and Java EE...",
            Comp: "My Skills",
            CompDesc: "I am an experienced web developer with expertise in HTML, CSS, and JavaScript, as well as modern frameworks like Bootstrap. I also have significant experience in backend development with Python, PHP, and Java, and in database management with MySQL and MongoDB. My skills also extend to artificial intelligence, particularly with TensorFlow for machine learning, and business intelligence with tools like Talend Open Studio. With this combination of skills, I am capable of designing and developing innovative software solutions for various projects.",
            Bac: "Bachelor's Degree in Mathematic B",
            BacDesc: "I obtained my bachelor's degree with honors, a true pride for me. It rewards my efforts and determination during my years of study. It is a great source of motivation to continue excelling and pursuing my academic ambitions.",
            BacPlace: "- Ibn Alhaytam High School",
            ensa: "National School of Applied Sciences of Fes",
            ensaDesc: "I joined the National School of Applied Sciences to become an engineer, meeting the required admission criteria. It is an important step in my academic journey and an opportunity that I embrace with enthusiasm. I am motivated to face the challenges ahead and acquire the skills necessary to succeed in the field of engineering.",
            ensaPlace: "- ENSAF",
            sp: "Specialization in Computer Engineering",
            spDesc: "After two years in scientific preparatory class, I joined the Computer Engineering specialization in my engineering school, ranking among the top 40 of my class. It is a significant step in my academic journey, and I am thrilled to have the opportunity to delve into the in-depth study of computer science. I am motivated to tackle the challenges that lie ahead and develop my skills to become a competent and accomplished computer engineer.",
            dip: "Graduated in Computer Engineering",
            dipDesc: "By 2025, Insha'Allah, I aspire to obtain my Bachelor's degree in Computer Engineering from the National School of Applied Sciences of Fes (ENSAF). I am determined to pursue the study program with determination and commitment to acquire the skills necessary to excel in this constantly evolving field. My ambition is to contribute to technological innovation and become a competent and accomplished professional in the field of computer science.",
     //----------------------------
     FrontEnd: "FrontEnd",
     langProg: "Programming Language",
     BD: "Database",
     Framworks: "Frameworks",
     BackEnd: "BackEnd",
     BI: "BI and Data Analysis",
     concDW: "Data Warehouse Design",
     SIG: "Geographic Information System",
     Res: "System and Network Administration",
     AI: "Artificial Intelligence",
     autre: "Other Technical Skills",
     merise: "MERISE Design",
     uml: "UML Modeling",
     PP: "Projects and Career Path",
     AppCon: "Application of Knowledge",
     projet: "Completed Project",
     parcour: "Academic Path",
     h: "Hours",
     p: "Projects",
     cof: "Cups of Coffee",
     certifs: "Certifications Obtained",
     programmation: "Programming",
     langues: "Languages",
     contactMe: "Contact Me",
     suivMoi: "Follow Me",
     UcanF: "You can follow or send me a message on my social networks",
     a: "Address",
     maison: "N 24 RUE 01 HY KARIMA",
     contINFO: "CONTACT INFO",
     //------------------------
     StIni: "Initiation Internship",
StIniDesc: "Development of a web application for hotel search.",
entr1: "ArtiWeb Digital Marketing Center Fez",
dateSt1: "July 2023",
StPFA: "PFA Application Internship",
StPFAdesc: "Development of a Responsive Web Application for the Digitalization of DCI Processes: Management of Fire Safety Audits and Emergency Response.",
StPFE: "PFE Internship"

    
       
        }
    },
    fr: {
        translation: {
            lang : 'Francais',
            home: 'Accueil',
            exp : "Expériences",
            comp : "Compétences",
            prjs : "Projets",
            parc : "Parcours",
            pers: 'Personnel',
            prof: 'Professionnel',
            contact: 'Contact',
            CompTech : "Compétences techniques",
            ExpProf : "Expérience professionnel",
            nom: "ILYAS MAKHLOUL ",
            statut: "Etudiant Ingénieur en Génie Informatique Ecole Nationale des Sciences Appliquée Fés , et je suis à la recherche d'un stage de fin d'étude PFE  (6mois à partie de janvier 2025)",
            DownCV : 'Télécharger CV',
            DownST : 'Demande de stage',
            etud : 'Etudiant ingénieurs',
            tel : 'Téléphone',
            email : 'E-mail',
            loc : 'Localisation',
            addr : 'Fés , Maroc ' , 
            DownCVA : 'Télecharger CV en anglais',
            prof : 'Profile',
            prof1 :  "Je suis élève ingénieur en génie informatique en troisième année de cycle ingénieur à l'École Nationale des Sciences Appliquées de Fès (bac+5). Je suis un programmeur passionné qui maîtrise plusieurs langages de programmation.",
            prof2 : "  Mon intérêt particulier se porte sur le développement des application web/andoid et des jeux. et tous ce qu’est AI - Machine learning - Deep Learning",
            do : "Qui ce que je fait !!!",
            AI : "AI Machine Learning",
            AIdesc : "je suis entrain d'apprendre les technologie en relation avec AI , machine learning (régression/classification) en python .",
            AppDev : "App Developement",
            AppDevDesc : "J'ai développé plusieurs applications bureautiques et pour Android. Vous pouvez les voir dans la section des projets ci-dessous.",
           API : 'API Developement',
           APIdesc : "J'ai déjà travaillé avec des API d'hôtels lors du développement de EasyStay pendant mon stage d'initiation.",
           WebDev : "Web Developement",
           WebDevDesc : "J'ai développé plusieurs applications web en utilisant différentes technologies telles que ASP.NET Core et Java EE...",
           Comp : "Mes Compétences",
           CompDesc : "Je suis un développeur web expérimenté avec une expertise en HTML, CSS et JavaScript, ainsi que des frameworks modernes comme Bootstrap. J'ai également une expérience significative en développement back-end avec Python, PHP et Java, et en gestion de bases de données comme MySQL et MongoDB. Mes compétences s'étendent également à l'intelligence artificielle, notamment avec TensorFlow pour le machine learning, et en business intelligence avec des outils comme Talend Open Studio. Avec cette combinaison de compétences, je suis capable de concevoir et de développer des solutions logicielles innovantes pour divers projets.",
          Bac : "Baccalauréat en Science Mathématiques B",
          BacDesc : "J'ai décroché mon bac avec mention bien, une véritable fierté pour moi. Cela récompense mes efforts et ma détermination durant mes années d'études. C'est une grande source de motivation pour continuer à exceller et poursuivre mes ambitions académiques.",
         BacPlace : "- Lycée Ibn Alhaytam",
   
         ensa : 'Ecole Nationale des Sciences Appliquée des Fés',
         ensaDesc :  "J'ai intégré l'École Nationale de Sciences Appliquées pour devenir ingénieur, en respectant les critères d'admission requis. C'est une étape importante dans mon parcours académique et une opportunité que je saisis avec enthousiasme. Je suis motivé à relever les défis qui m'attendent et à acquérir les compétences nécessaires pour réussir dans le domaine de l'ingénierie.",
     ensaPlace : "- ENSAF",

     sp : "spécialité en Génie Informatique",
     spDesc  : "   Après deux années en classe préparatoire scientifique, j'ai intégré la spécialité Génie Informatique dans mon école d'ingénieurs en étant classé parmi les 40 premiers de ma promotion. C'est une étape importante dans mon parcours académique et je suis ravi d'avoir l'opportunité de me plonger dans l'étude approfondie de l'informatique. Je suis motivé à relever les défis qui se présenteront à moi et à développer mes compétences pour devenir un ingénieur en informatique compétent et accompli.",
      dip : "Diplomé en Génie Informatique",
      dipDesc : "D'ici 2025 Insha-allah, j'aspire à obtenir mon diplôme d'ingénieur en Génie Informatique de l'École Nationale des Sciences Appliquées de Fès (ENSAF). Je suis résolu à suivre avec détermination et engagement le programme d'études afin d'acquérir les compétences nécessaires pour exceller dans ce domaine en constante évolution. Mon ambition est de contribuer à l'innovation technologique et de devenir un professionnel compétent et accompli dans le domaine de l'informatique.",
      //---------------------------------
      FrontEnd : 'FrontEnd',
      langProg : 'Langage de programmation',
      BD : 'Base de données',
      Framworks : 'Framworks',
      BackEnd : 'BackEnd',
      BI  : 'BI et analyse de données',
      concDW : 'Conception des entrepôts de données',
      SIG : "Système d'information Géographique",
      Res  : "Administration Systèmes et Réseaux",
      AI : 'Intelligence artificielle',
      autre : 'Autre compétences techniques',
      merise : 'Conception MERISE',
      uml : 'Modélisation UML',
      PP : 'Projets et Parcours de',
      AppCon : 'Application des connaissances',
      projet : 'Projet réalisé',
      parcour : 'Parcour Académique',
      h : 'Heurs',
      p : 'Projets',
      cof : 'Tasses de café',
      certifs : 'certification obtenue',
      programmation : 'Programmation',
      langues : 'Langues',
      contactMe : 'Contacter Moi',
      suivMoi : 'Suivre Moi' , 
      UcanF : 'vous pouvez me suivre ou envoyer un message sur mes réseaux sociaux',
      a : 'Addresse',
      maison : 'N 24 RUE  01 HY KARIMA',
      contINFO : 'CONTACT INFOS',
      send : 'Envoyer',
     
      /*--------------------------------------------------------------------*/
      StIni : "Stage d'initiation ",
      StIniDesc : "Développement d'une application web permettant la recherche d'hôtels.",
      entr1 : "Centre de marketing digitale ArtiWeb Fés",
      dateSt1 : "Juillet 2023",
      StPFA : "Stage d'application PFA",
      StPFAdesc : "Réalisation d'une Application Web Responsive pour la Digitalisation des Processus DCI : Gestion des Audits de Sécurité Incendie et Intervention d'Urgence",
      StPFE : "Stage PFE"
    
    }
    },
    ar: {
        translation: {
            lang : 'العربية',
            home: 'الصفحة الرئيسية',
            exp: "الخبرات",
comp: "المهارات",
prjs: "المشاريع",
parc: "المسار المهني"
,
            pers: 'شخصي',
            prof: 'مهني',
            contact: 'اتصل',
            nom: "إلياس مخلول",
            statut: "طالب مهندس في هندسة الحاسوب في المدرسة الوطنية للعلوم التطبيقية بفاس، وأنا أبحث عن تدريب نهاية الدراسة (مدة 6 أشهر ابتداءً من يناير 2025).",
            DownCV: 'تحميل السيرة الذاتية',
            DownST: 'تطبيق للتدريب' , 
            etud: 'طالب هندسة',
            tel: 'الهاتف',
            CompTech : "المهارات التقنية",
            ExpProf :'الخبرة المهنية',
            email: 'البريد الإلكتروني',
            loc: 'الموقع',
            addr: 'فاس، المغرب',
            DownCVA: 'تحميل السيرة الذاتية باللغة الإنجليزية',
            prof: 'الملف الشخصي',
            prof1: "أنا طالب هندسة كمبيوتر في السنة الثالتة من دورة الهندسة في المدرسة الوطنية للعلوم التطبيقية بفاس (باك + 5)، أنا مبرمج متحمس يتقن العديد من لغات البرمجة.",
            prof2: "اهتمامي الخاص يكمن في تطوير تطبيقات الويب / Android والألعاب، وكل ما يتعلق بالذكاء الاصطناعي - التعلم الآلي - التعلم العميق." ,
            do: "ماذا أفعل !!!",
            AI: "الذكاء الصناعي وتعلم الآلة",
            AIdesc: "أنا حالياً أتعلم التقنيات المتعلقة بالذكاء الصناعي وتعلم الآلة (الانحدار/التصنيف) باستخدام Python.",
            AppDev: "تطوير التطبيقات",
            AppDevDesc: "لقد قمت بتطوير العديد من التطبيقات لسطح المكتب والأندرويد. يمكنك رؤيتها في قسم المشاريع أدناه.",
            API: 'تطوير واجهات البرمجة (API)',
            APIdesc: "لقد عملت مع واجهات برمجة التطبيقات (API) للفنادق أثناء تطوير EasyStay خلال فترة التدريب الخاصة بي.",
            WebDev: "تطوير الويب",
            WebDevDesc: "لقد قمت بتطوير العديد من تطبيقات الويب باستخدام تقنيات مختلفة مثل ASP.NET Core و Java EE...",
               Comp: "مهاراتي",
            CompDesc: "أنا مطور ويب متمرس بخبرة في HTML و CSS و JavaScript، بالإضافة إلى الإطارات الحديثة مثل Bootstrap. لدي أيضًا خبرة كبيرة في تطوير الجزء الخلفي للتطبيق مع Python و PHP و Java، وفي إدارة قواعد البيانات مثل MySQL و MongoDB. تمتد مهاراتي أيضًا إلى الذكاء الاصطناعي، بشكل خاص باستخدام TensorFlow لتعلم الآلة، وإلى الذكاء التجاري باستخدام أدوات مثل Talend Open Studio. من خلال هذا التوازن بين المهارات، أستطيع تصميم وتطوير حلول برمجية مبتكرة لمشاريع متنوعة.",
            Bac: "شهادة البكالوريا في العلوم الرياضياتية ب ",
            BacDesc: "حصلت على شهادة البكالوريوس بتقدير جيد جدًا، وهو مصدر فخر حقيقي بالنسبة لي. إنه يكافأ على جهودي وإصراري خلال سنوات دراستي. إنه مصدر كبير للتحفيز لمواصلة التفوق ومتابعة طموحاتي الأكاديمية.",
            BacPlace: "- ثانوية ابن الهيثم",
            ensa: "المدرسة الوطنية للعلوم التطبيقية بفاس",
            ensaDesc: "انضممت إلى المدرسة الوطنية للعلوم التطبيقية لأصبح مهندسًا، مستوفيًا المعايير اللازمة للقبول. إنها خطوة مهمة في رحلتي الأكاديمية وفرصة أتمنى أن أستفيد منها بحماس. أنا متحمس لمواجهة التحديات المقبلة واكتساب المهارات اللازمة للنجاح في مجال الهندسة.",
            ensaPlace: "- ENSAF",
            sp: "تخصص في هندسة الكمبيوتر",
            spDesc: "بعد عامين في الصف العلمي التحضيري، انضممت إلى تخصص هندسة الكمبيوتر في مدرستي الهندسية، محتلاً المرتبة الـ40 من بين زملائي في الدفعة. إنها خطوة مهمة في رحلتي الأكاديمية، وأنا متحمس للفرصة التي ستمكنني من التعمق في دراسة علوم الكمبيوتر بشكل عميق. أنا متحمس لمواجهة التحديات التي تنتظرني وتطوير مهاراتي لأصبح مهندس كمبيوتر متميزًا ومتمكنًا.",
            dip: "خريج في هندسة الكمبيوتر",
        
            dipDesc: "بحلول عام 2025، إن شاء الله، أتطلع للحصول على شهادة مهندس دولة في الهندسة المعلوماتية.",
            //-------------------
            
                FrontEnd: "الواجهة الأمامية",
                langProg: "لغة البرمجة",
                BD: "قاعدة البيانات",
                Framworks: "الأطر",
                BackEnd: "الواجهة الخلفية",
                BI: "تحليل البيانات وذكاء الأعمال",
                concDW: "تصميم مستودعات البيانات",
                SIG: "نظام المعلومات الجغرافية",
                Res: "إدارة الأنظمة والشبكات",
                AI: "الذكاء الاصطناعي",
                autre: "مهارات تقنية أخرى",
                merise: "تصميم ميريز",
                uml: "نمذجة UML",
                PP: "المشاريع والمسار المهني",
                AppCon: "تطبيق المعرفة",
                projet: "مشروع منجز",
                parcour: "المسار الأكاديمي",
                h: "ساعات",
                p: "مشاريع",
                cof: "أكواب القهوة",
                certifs: "الشهادات المكتسبة",
                programmation: "البرمجة",
                langues: "اللغات",
                contactMe: "اتصل بي",
                suivMoi: "تابعني",
                UcanF: "يمكنك متابعتي أو إرسال رسالة على شبكات التواصل الاجتماعي الخاصة بي",
                a: "العنوان",
                maison: "ن 24 شارع 01 حي كريمة",
                contINFO: "معلومات الاتصال",
                send: "إرسال",
                //------------------------------------------
                StIni: "تدريب تمهيدي",
                StIniDesc: "تطوير تطبيق ويب للبحث عن الفنادق.",
                entr1: "مركز التسويق الرقمي ArtiWeb فاس",
                dateSt1: "يوليو 2023",
                StPFA: "تدريب تطبيق PFA",
                StPFAdesc: "إنجاز تطبيق ويب متجاوب لرقمنة عمليات DCI: إدارة تدقيقات السلامة من الحرائق والتدخلات الطارئة.",
                StPFE: "تدريب مشروع نهاية الدراسة"

    
        }
    },


    es: {
        translation: {
            lang: 'español',
            home: 'Inicio',
            exp: "Experiencias",
comp: "Habilidades",
prjs: "Proyectos",
parc: "Trayectoria"
,
            pers: 'Personal',
            prof: 'Profesional',
            contact: 'Contacto',
            CompTech : "Habilidades Técnicas",
            ExpProf : "Experiencia Profesional", 
            nom: "ILYAS MAKHLOUL",
            statut: "Estudiante de ingeniería en Ingeniería Informática en la Escuela Nacional de Ciencias Aplicadas de Fez, y estoy buscando una pasantía de fin de estudios (6 meses a partir de enero de 2025).",
            DownCV: 'Descargar CV',
            DownST: 'Solicitud de pasantía',
            etud: 'Estudiante de ingeniería',
            tel: 'Teléfono',
            email: 'Correo electrónico',
            loc: 'Ubicación',
            addr: 'Fes, Marruecos',
            DownCVA: 'Descargar CV en inglés',
            prof: 'Perfil',
            prof1: "Soy estudiante de ingeniería informática en el tercer año del ciclo de ingeniería en la Escuela Nacional de Ciencias Aplicadas de Fez (bachillerato +5). Soy un programador apasionado con dominio de varios lenguajes de programación.",
            prof2: "Mi interés particular se centra en el desarrollo de aplicaciones web/Android y juegos, y en todo lo relacionado con AI - Machine learning - Deep Learning",
            do: "¿Qué hago?",
            AI: "Aprendizaje automático de inteligencia artificial",
            AIdesc: "Actualmente estoy aprendiendo tecnologías relacionadas con AI, aprendizaje automático (regresión/clasificación) en Python.",
            AppDev: "Desarrollo de aplicaciones",
            AppDevDesc: "He desarrollado varias aplicaciones de escritorio y para Android. Puedes verlas en la sección de proyectos a continuación.",
            API: 'Desarrollo de API',
            APIdesc: "Ya he trabajado con API de hoteles durante el desarrollo de EasyStay durante mi período de prácticas.",
            WebDev: "Desarrollo web",
            WebDevDesc: "He desarrollado varias aplicaciones web utilizando diversas tecnologías como ASP.NET Core y Java EE...",
            Comp: "Mis habilidades",
            CompDesc: "Soy un desarrollador web experimentado con experiencia en HTML, CSS y JavaScript, así como en frameworks modernos como Bootstrap. También tengo experiencia significativa en desarrollo backend con Python, PHP y Java, y en gestión de bases de datos como MySQL y MongoDB. Mis habilidades también se extienden a la inteligencia artificial, particularmente con TensorFlow para el aprendizaje automático, y en inteligencia empresarial con herramientas como Talend Open Studio. Con esta combinación de habilidades, soy capaz de diseñar y desarrollar soluciones de software innovadoras para diversos proyectos.",
            Bac: "Licenciatura en Matemáticas y Ciencias",
            BacDesc: "Obtuve mi licenciatura con honores, un verdadero orgullo para mí. Premia mis esfuerzos y determinación durante mis años de estudio. Es una gran fuente de motivación para seguir sobresaliendo y perseguir mis ambiciones académicas.",
            BacPlace: "- Instituto Ibn Alhaytam",
            ensa: "Escuela Nacional de Ciencias Aplicadas de Fes",
            ensaDesc: "Me uní a la Escuela Nacional de Ciencias Aplicadas para convertirme en ingeniero, cumpliendo con los criterios de admisión requeridos. Es un paso importante en mi trayectoria académica y una oportunidad que abrazo con entusiasmo. Estoy motivado para enfrentar los desafíos que se avecinan y adquirir las habilidades necesarias para tener éxito en el campo de la ingeniería.",
            ensaPlace: "- ENSAF",
            sp: "Especialización en Ingeniería Informática",
            spDesc: "Después de dos años en la clase preparatoria científica, me uní a la especialización en Ingeniería Informática en mi escuela de ingeniería, clasificándome entre los 40 mejores de mi promoción. Es un paso significativo en mi trayectoria académica y estoy encantado de tener la oportunidad de sumergirme en el estudio profundo de la informática. Estoy motivado para enfrentar los desafíos que se me presenten y desarrollar mis habilidades para convertirme en un ingeniero informático competente y exitoso.",
            dip: "Graduado en Ingeniería Informática",
            dipDesc: "Para 2025, Insha'Allah, aspiro a obtener mi licenciatura en Ingeniería Informática de la Escuela Nacional de Ciencias Aplicadas de Fes (ENSAF). Estoy decidido a seguir el programa de estudios con determinación y compromiso para adquirir las habilidades necesarias para sobresalir en este campo en constante evolución. Mi ambición es contribuir a la innov",
      //----------------------------
      FrontEnd: "FrontEnd",
      langProg: "Lenguaje de programación",
      BD: "Base de datos",
      Framworks: "Frameworks",
      BackEnd: "BackEnd",
      BI: "BI y análisis de datos",
      concDW: "Diseño de almacenes de datos",
      SIG: "Sistema de Información Geográfica",
      Res: "Administración de sistemas y redes",
      AI: "Inteligencia artificial",
      autre: "Otras habilidades técnicas",
      merise: "Diseño MERISE",
      uml: "Modelado UML",
      PP: "Proyectos y trayectoria",
      AppCon: "Aplicación del conocimiento",
      projet: "Proyecto realizado",
      parcour: "Trayectoria académica",
      h: "Horas",
      p: "Proyectos",
      cof: "Tazas de café",
      certifs: "Certificaciones obtenidas",
      programmation: "Programación",
      langues: "Idiomas",
      contactMe: "Contáctame",
      suivMoi: "Sígueme",
      UcanF: "Puedes seguirme o enviarme un mensaje en mis redes sociales",
      a: "Dirección",
      maison: "N 24 RUE 01 HY KARIMA",
      contINFO: "INFORMACIÓN DE CONTACTO",
      send: "Enviar" , 
      //-----------------------------------------
      StIni: "Pasantía de Iniciación",
StIniDesc: "Desarrollo de una aplicación web para la búsqueda de hoteles.",
entr1: "Centro de Marketing Digital ArtiWeb Fez",
dateSt1: "Julio 2023",
StPFA: "Pasantía de Aplicación PFA",
StPFAdesc: "Realización de una Aplicación Web Responsive para la Digitalización de los Procesos de DCI: Gestión de Auditorías de Seguridad contra Incendios e Intervención de Emergencia.",
StPFE: "Pasantía PFE"


      
      
        }
},
    al:{
    "translation": {
        "lang": "Deutsch",
        "home": "Startseite",
        exp: "Erfahrungen",
comp: "Kompetenzen",
prjs: "Projekte",
parc: "Werdegang"
,
        "pers": "Persönlich",
        "prof": "Beruflich",
        "contact": "Kontakt",
        "nom": "ILYAS MAKHLOUL",
        "CompTech" : "Technische Fähigkeiten",
        "ExpProf" : "Berufserfahrung", 
        "statut": "Ingenieurstudent im Fachbereich Informatik an der Nationalen Hochschule für Angewandte Wissenschaften Fes, und ich suche ein Abschlusspraktikum (6 Monate ab Januar 2025).",
        "DownCV": "Lebenslauf herunterladen",
        "DownST": "Praktikumsanfrage",
        "etud": "Ingenieurstudent",
        "tel": "Telefon",
        "email": "E-Mail",
        "loc": "Ort",
        "addr": "Fès, Marokko",
        "DownCVA": "Lebenslauf auf Englisch herunterladen",
        "prof": "Profil",
        "prof1": "Ich bin ein Informatik-Ingenieurstudent im dritten Jahr des Ingenieurstudiums an der Nationalen Schule für Angewandte Wissenschaften in Fès (Bac+5). Ich bin ein leidenschaftlicher Programmierer und beherrsche mehrere Programmiersprachen.",
        "prof2": "Mein besonderes Interesse gilt der Entwicklung von Web-/Android-Anwendungen und Spielen sowie allem im Bereich KI, maschinelles Lernen und Deep Learning.",
        "do": "Was ich mache!!!",
        "AI": "KI und maschinelles Lernen",
        "AIdesc": "Ich lerne derzeit Technologien im Zusammenhang mit KI und maschinellem Lernen (Regression/Klassifikation) in Python.",
        "AppDev": "App-Entwicklung",
        "AppDevDesc": "Ich habe mehrere Desktop- und Android-Anwendungen entwickelt. Sie können sie im Abschnitt Projekte unten sehen.",
        "API": "API-Entwicklung",
        "APIdesc": "Ich habe bereits mit Hotel-APIs während der Entwicklung von EasyStay während meines Einführungspraktikums gearbeitet.",
        "WebDev": "Webentwicklung",
        "WebDevDesc": "Ich habe mehrere Webanwendungen unter Verwendung verschiedener Technologien wie ASP.NET Core und Java EE entwickelt...",
        "Comp": "Meine Fähigkeiten",
        "CompDesc": "Ich bin ein erfahrener Webentwickler mit Fachkenntnissen in HTML, CSS und JavaScript sowie modernen Frameworks wie Bootstrap. Ich habe auch umfangreiche Erfahrung in der Backend-Entwicklung mit Python, PHP und Java sowie in der Datenbankverwaltung mit MySQL und MongoDB. Meine Fähigkeiten erstrecken sich auch auf künstliche Intelligenz, insbesondere mit TensorFlow für maschinelles Lernen, und auf Business Intelligence mit Tools wie Talend Open Studio. Mit dieser Kombination von Fähigkeiten bin ich in der Lage, innovative Softwarelösungen für verschiedene Projekte zu entwerfen und zu entwickeln.",
        "Bac": "Abitur in Mathematik und Naturwissenschaften",
        "BacDesc": "Ich habe mein Abitur mit Auszeichnung bestanden, eine wahre Ehre für mich. Dies belohnt meine Anstrengungen und Entschlossenheit während meiner Schuljahre. Es ist eine große Motivation, weiterhin herausragende Leistungen zu erbringen und meine akademischen Ambitionen fortzusetzen.",
        "BacPlace": "- Lycée Ibn Alhaytam",
        "ensa": "École Nationale des Sciences Appliquées de Fès",
        "ensaDesc": "Ich bin der École Nationale des Sciences Appliquées beigetreten, um Ingenieur zu werden, unter Berücksichtigung der erforderlichen Zulassungskriterien. Dies ist ein wichtiger Schritt in meinem akademischen Werdegang und eine Gelegenheit, die ich mit Begeisterung ergreife. Ich bin motiviert, die bevorstehenden Herausforderungen anzunehmen und die erforderlichen Fähigkeiten zu erwerben, um im Ingenieurwesen erfolgreich zu sein.",
        "ensaPlace": "- ENSAF",
        "sp": "Spezialisierung in Informatik",
        "spDesc": "Nach zwei Jahren in einem wissenschaftlichen Vorbereitungskurs habe ich mich für die Spezialisierung Informatik an meiner Ingenieursschule entschieden und gehöre zu den besten 40 meiner Klasse. Dies ist ein wichtiger Meilenstein in meiner akademischen Laufbahn, und ich freue mich darauf, mich intensiv mit Informatik zu beschäftigen. Ich bin motiviert, den Herausforderungen zu begegnen, die auf mich zukommen, und meine Fähigkeiten zu entwickeln, um ein kompetenter und erfolgreicher Informatikingenieur zu werden.",
        "dip": "Abschluss in Informatik",
        "dipDesc": "Bis 2025, Insha-Allah, strebe ich meinen Abschluss in Informatik von der École Nationale des Sciences Appliquées de Fès (ENSAF) an. Ich bin entschlossen, das Studienprogramm mit Entschlossenheit und Engagement zu absolvieren, um die erforderlichen Fähigkeiten zu erwerben, um in diesem sich ständig weiterentwickelnden Bereich erfolgreich zu sein. Mein Ziel ist es, zur technologischen Innovation beizutragen und ein kompetenter und erfolgreicher Fachmann im Bereich Informatik zu werden.",
        //--------------------------------
        FrontEnd: "FrontEnd",
        langProg: "Programmiersprache",
        BD: "Datenbank",
        Framworks: "Frameworks",
        BackEnd: "BackEnd",
        BI: "BI und Datenanalyse",
        concDW: "Datenbankentwurf",
        SIG: "Geoinformationssystem",
        Res: "System- und Netzwerkadministration",
        AI: "Künstliche Intelligenz",
        autre: "Weitere technische Fähigkeiten",
        merise: "MERISE-Design",
        uml: "UML-Modellierung",
        PP: "Projekte und Karriereweg",
        AppCon: "Anwendung von Wissen",
        projet: "Abgeschlossenes Projekt",
        parcour: "Akademischer Weg",
        h: "Stunden",
        p: "Projekte",
        cof: "Tassen Kaffee",
        certifs: "Zertifizierungen",
        programmation: "Programmierung",
        langues: "Sprachen",
        contactMe: "Kontaktiere mich",
        suivMoi: "Folge mir",
        UcanF: "Sie können mir folgen oder eine Nachricht in meinen sozialen Netzwerken senden",
        a: "Adresse",
        maison: "N 24 RUE 01 HY KARIMA",
        contINFO: "KONTAKTINFO",
        send: "Senden" , 
        //-----------------------------
        StIni: "Einführungspraktikum",
StIniDesc: "Entwicklung einer Webanwendung zur Hotelsuche.",
entr1: "ArtiWeb Digital Marketing Center Fès",
dateSt1: "Juli 2023",
StPFA: "PFA-Anwendungspraktikum",
StPFAdesc: "Entwicklung einer responsiven Webanwendung zur Digitalisierung der DCI-Prozesse: Verwaltung von Brandsicherheitsaudits und Notfalleinsätzen.",
StPFE: "PFE-Praktikum"


    }
}

};


// Initialiser i18next
i18next.use(i18nextBrowserLanguageDetector).init({
    resources,
    fallbackLng: 'fr',
    debug: true
}, function(err, t) {
    // Initialize jquery-i18next
    jqueryI18next.init(i18next, $);

    // Traduire le contenu au chargement de la page
    updateContent();
});

// Fonction pour changer la langue
function changeLanguage(lng) {
    i18next.changeLanguage(lng, updateContent);
}

// Fonction pour mettre à jour le contenu traduit
function updateContent() {
    $('body').localize();
}
